# Generated by Django 4.2.6 on 2023-10-06 19:33

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='bg_image',
            field=models.ImageField(upload_to='images/%Y%m%d', validators=[blog.models.validate_image_dimensions]),
        ),
    ]
