# Generated by Django 4.2.6 on 2023-10-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bg_image',
            field=models.ImageField(null=True, upload_to='images/%Y%m%d/background_images'),
        ),
    ]
