# Generated by Django 4.2.6 on 2023-10-09 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_bg_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactPage',
        ),
    ]
